[package]
name = "genvm-modules-interfaces"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.97"
bytes = { version = "1.11.0", features = ["serde"] }
genlayer_calldata = { path = "../../executors/v0.3.x/executor/crates/calldata" }
num-bigint = "0.4"
num-traits = "0.2"
primitive-types = { version = "0.13", features = ["impl-serde"] }
regex = { version = "1.11.1", default-features = false, features = ["std"] }
serde = { version = "1.0.219", features = ["rc", "derive"] }
serde_bytes = "0.11.17"
serde_derive = "1.0.219"
serde_json = "1.0.140"
tokio = { version = "1.44.1", features = [
    "rt",
    "rt-multi-thread",
    "net",
    "time",
    "macros",
    "sync",
], default-features = false }
